---
#
# install xpack suite for elastic services
#

- name: Check if elasticsearch xpack is installed
  stat: path=/usr/share/elasticsearch/plugins/x-pack
  register: check_es_xpack_path
  become: true

- name: Check if kibana xpack is installed
  stat: path=/usr/share/kibana/plugins/x-pack
  register: check_kibana_xpack_path
  become: true

- name: Check if logstash xpack is installed
  shell: /usr/share/logstash/bin/logstash-plugin list | grep x-pack
  register: check_logstash_xpack_installed
  failed_when: check_logstash_xpack_installed.rc == 2
  ignore_errors: true
  changed_when: false
  become: true

- name: Install xpack for elasticsearch
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack -b
  when: install_elasticsearch_xpack and check_es_xpack_path.stat.exists == False
  ignore_errors: true
  become: true

- name: Install xpack for kibana, this might take a while
  command: /usr/share/kibana/bin/kibana-plugin install x-pack
  when: install_kibana_xpack and check_kibana_xpack_path.stat.exists == False
  ignore_errors: true
  become: true

- name: Install xpack for logstash
  command: /usr/share/logstash/bin/logstash-plugin install x-pack -b
  when: install_logstash_xpack and check_logstash_xpack_installed.stdout == ""
  ignore_errors: true
  become: true
