---
#
# install/run packetbeat elk client
#
- name: Install packetbeat rpms
  yum:
    name: [packetbeat, libpcap]
  become: true
  when: (logging_backend != 'fluentd')

- name: Generate packetbeat configuration template
  template:
    src=packetbeat.yml.j2
    dest=/etc/packetbeat/packetbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  when: (logging_backend != 'fluentd')
  register: packetbeat_needs_restart

- name: Start packetbeat service
  command: systemctl start packetbeat.service
  ignore_errors: true
  become: true
  when: ((packetbeat_needs_restart != 0) and (logging_backend != 'fluentd'))

- name: Setup packetbeat service
  service: name=packetbeat state=started enabled=true
  become: true
  when: (logging_backend != 'fluentd')
