---
#
# Install/run fluentd
#

- name: Copy fluentd yum repo file
  copy:
    src=fluentd.repo
    dest=/etc/yum.repos.d/fluentd.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Import fluentd GPG Key
  rpm_key: key=https://packages.treasuredata.com/GPG-KEY-td-agent
    state=present

- name: Install fluentd
  yum:
    name: [td-agent, gcc]
  become: true

- name: Setup fluentd configuration files
  template:
    src=td-agent.conf.j2
    dest=/etc/td-agent/td-agent.conf
    owner=root
    group=root
    mode=0644
  become: true
  register: fluentd_needs_restart

# this is for compability
- name: Load OpenSSL CA Extended Configuration
  template:
    src=openssl_extras.cnf.j2
    dest=/etc/pki/tls/openssl_extras.cnf
    owner=root
    group=root
    mode=0644
  become: true

# this is for compatibility
- name: Check OpenSSL SANs (SubjectAltName) entry for CA
  shell: grep "{{ ansible_default_ipv4.address }}" /etc/pki/tls/openssl.cnf | wc -l
  ignore_errors: true
  register: subjectAltName_exists
  tags:
    # Skip ANSIBLE0012 Commands should not change things if nothing needs doing
    # Need to understand if an entry exists
    - skip_ansible_lint
  become: true

# this is for compability
- name: Add OpenSSL SANs (SubjectAltName) entry for CA
  lineinfile:
    dest: /etc/pki/tls/openssl.cnf
    line: 'subjectAltName = "IP: {{ ansible_default_ipv4.address }}"'
    regexp: '^ Extensions for a typical CA'
    insertbefore: '# Extensions for a typical CA'
    backup: yes
  when: subjectAltName_exists.stdout|int == 0
  become: true

- name: Install fluentd elasticsearch plugin
  gem:
    name=fluent-plugin-elasticsearch
    state=latest
    include_dependencies=yes
    user_install=no
    executable=/usr/sbin/td-agent-gem
  become: true
  ignore_errors: false

- name: Install fluentd beats plugin
  gem:
    name=fluent-plugin-beats
    state=latest
    include_dependencies=yes
    user_install=no
    executable=/usr/sbin/td-agent-gem
  become: true
  ignore_errors: false

- name: Load filebeat JSON index template
  uri:
    url: http://localhost:9200/_template/filebeat?pretty
    method: POST
    body: "{{ lookup('file', 'filebeat-index-template.json') }}"
    body_format: json
  ignore_errors: true
  become: true

- name: Start fluentd service
  command: systemctl start td-agent.service
  ignore_errors: true
  when: fluentd_needs_restart != 0
  become: true

- name: Setup fluentd service
  service: name=td-agent state=started enabled=true
  become: true
